### ISSUE TITLE
Unable to install shap on python 3.11 doubt to  numba cannot install on Python version 3.11.2

### ISSUE THREAD

**Issue by AlexNoelHdz** [pydata/sparse#588] opened 2023-04-14 03:19 UTC
**Describe the bug**
Unable to install shap on python 3.11 doubt to  numba cannot install on Python version 3.11.2

**To Reproduce**
pip install shap
Collecting shap
  Downloading shap-0.41.0.tar.gz (380 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.1/380.1 kB 394.7 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.24.2)
Requirement already satisfied: scipy in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.10.1)
Requirement already satisfied: scikit-learn in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.2.2)
Requirement already satisfied: pandas in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.5.3)
Collecting tqdm>4.25.0
  Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 711.2 kB/s eta 0:00:00
Requirement already satisfied: packaging>20.9 in c:\users\anhernan\appdata\roaming\python\python311\site-packages (from shap) (23.0)
Collecting slicer==0.0.7
  Downloading slicer-0.0.7-py3-none-any.whl (14 kB)
Collecting numba
  Downloading numba-0.56.4.tar.gz (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 1.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\anhernan\AppData\Local\Temp\pip-install-j5quxlxv\numba_465c650efbd849728c6dbd5826d7dbea\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\anhernan\AppData\Local\Temp\pip-install-j5quxlxv\numba_465c650efbd849728c6dbd5826d7dbea\setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Expected behavior**
Being able to install shap

**System**
 - OS and version: Windows 11

**Comment by hameerabbasi** [comment] 2023-04-14 13:37
Duplicate of #584

**Closed** 2023-04-14 13:37 UTC
Labels: type:bug
