### ISSUE TITLE
DOK does not support slicing

### ISSUE THREAD

**Issue by jdlesage** [pydata/sparse#292] opened 2019-09-27 09:27 UTC
If I create a dask array from a DOK matrix. Then `_meta` attribute of dask array is a numpy dense array instead of DOK

**Example:**
```python
In [1]: import sparse

In [2]: import dask.array as da

In [10]: arr = sparse.DOK((10, 10))

In [11]: da_arr = da.from_array(arr)

In [12]: da_arr._meta
Out[12]: array([], shape=(0, 0), dtype=float64)
```

**Additional info**
I tested using this unit test from dask: https://github.com/dask/dask/blob/master/dask/array/tests/test_sparse.py#L215. I replaced COO by DOK
This test https://github.com/dask/dask/blob/master/dask/array/utils.py#L88 raises an exception because indexing by slices is not supported in DOK:

```
In [16]: arr[(tuple(slice(0, 0, None) for _ in range(arr.ndim)))]
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-16-a01fe24bb58f> in <module>
----> 1 arr[(tuple(slice(0, 0, None) for _ in range(arr.ndim)))]

***/sparse/dok.py in __getitem__(self, key)
    243
    244         if not all(isinstance(i, Integral) for i in key):
--> 245             raise NotImplementedError('All indices must be integers'
    246                                       ' when getting an item.')
    247

NotImplementedError: All indices must be integers when getting an item.
```

I am not sure how to fix that. Add support in DOK ? Add a specific case for DOK in dask ? What do you think ?

**Comment by hameerabbasi** [comment] 2019-09-27 09:32
Ahh, I see. I think at this point it would be better to just support `COO`, then add `DOK` support in the future.

**Comment by jdlesage** [comment] 2019-09-27 09:34
Fine for me 👍

**Comment by hameerabbasi** [comment] 2020-07-07 12:41
Duplicate of #298.

**Closed by hameerabbasi** 2020-07-07 12:41 UTC
Labels: type:duplicate
