### ISSUE TITLE
How can I use COO.data of shape (N, 6) instead of (N,)?

### ISSUE THREAD

**Issue by Haetsal-Lee** [pydata/sparse#352] opened 2020-05-26 05:49 UTC
**Description**
I want to use sparse.COO to represent points in 3D and, their normal and RGB. So my data will be of shape (N, 6) for each coordinate.

I am aware of that I can make COO array of shape (Dx, Dy, Dz, 6). But since each channel of RGB will be handled separately, it is far from my objective.

**Comment by hameerabbasi** [comment] 2020-05-26 08:45
Hello, is this resolved?

**Comment by hameerabbasi** [comment] 2020-05-26 08:57
Hello. Currently, this isn't possible.

**Comment by hameerabbasi** [comment] 2020-05-26 09:20
Duplicate of #227, closing as that one is the canonical issue.

**Closed by hameerabbasi** 2020-05-26 09:20 UTC
Labels: type:enhancement
